create table if not exists users (
    id bigint generated by default as identity primary key,
    email varchar(128),
    login varchar(128),
    name varchar(128),
    birthday date
);

create table if not exists users_friends(
    user_id bigint not null references users(id) on delete cascade,
    friend_id bigint not null references users(id) on delete cascade,
    primary key (user_id, friend_id)
);

create table if not exists films(
    id bigint primary key,
    uploader_id bigint not null references users(id) on delete cascade,
    title varchar(255) not null,
    description varchar(200),
    release_date date,
    duration bigint not null,
    mpa_id int references mpa_ratings(id) on delete set null
);

create table if not exists film_likes(
    film_id bigint not null references films(id) on delete cascade,
    user_id bigint not null references users(id) on delete cascade,
    primary key (film_id, user_id)
);

create table if not exists mpa_ratings(
    id int generated by default as identity primary key,
    name varchar(20) not null
);

create table if not exists film_genres(
    film_id bigint not null references films(id) on delete cascade,
    genre_id bigint not null references genres(id) on delete cascade,
    primary key(film_id, genre_id)
);

create table if not exists genres(
    id int generated by default as identity primary key,
    name varchar(50) not null
);